AllCops:
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - bin/**/*
    - db/migrate/20190725084316_devise_create_users.rb
    - config/environments/production.rb
    - config/puma.rb
    - test/**/*
  TargetRubyVersion: 2.7.1
Style/FrozenStringLiteralComment:
  Enabled: false
Style/RaiseArgs:
  EnforcedStyle: compact
Rails:
  Enabled: true
Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"
Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - config/routes.rb
    - app/models/concerns/**/*
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 200
Metrics/MethodLength:
  Max: 20
Metrics/ClassLength:
  Max: 1500
Rails/SkipsModelValidations:
  Blacklist:
    - decrement!
    - decrement_counter
    - increment!
    - increment_counter
    - toggle!
    - update_all
    - update_attribute
    - update_column
    - update_columns
    - update_counters
